"""
Phase 2 Tests: AGNI Event Intelligence Engine
=============================================
Validates:
1. Event Ingestion Service
2. Manual Event Creation Workflow
3. Strict Event Validation & Bounds Checking
4. Canonical Normalization
5. Explainable Risk Scoring (all 8 explicit factors verified separately)
6. Transmission-Path Generation
7. Global Signal Field API Integration & Backend Object Retrieval
"""

import pytest
from datetime import datetime, timezone
from fastapi.testclient import TestClient

from agni.data.schemas import (
    Event,
    RiskSignal,
    RiskSignalComponent,
    TransmissionLink,
    EventIntelligenceResult,
)
from agni.events.ingestion import EventIngestionService
from agni.events.validation import EventValidator, ValidationError
from agni.events.normalization import EventNormalizer
from agni.events.features import FeatureCalculator
from agni.events.risk_scorer import ExplainableRiskScorer
from agni.events.transmission import TransmissionGenerator
from agni.events.workflow import EventWorkflow
from backend.app.repositories.intel_store import intel_store
from backend.app.main import app

client = TestClient(app)


# ── 1. VALIDATION TESTS ──────────────────────────────────────────────────────

def test_event_validation_success():
    evt = Event(
        event_id="evt-val-test-01",
        title="Baltic Subsea Cable Telemetry Severance",
        description="Multiple fiber telecommunication lines severed in the Baltic Sea corridor.",
        country="Estonia / Finland",
        region="Northern Europe",
        latitude=59.4370,
        longitude=24.7536,
        severity="high",
        confidence=0.94,
    )
    is_valid, errors = EventValidator.validate_event(evt)
    assert is_valid is True
    assert len(errors) == 0


def test_event_validation_out_of_bounds_coordinates():
    raw = {
        "title": "Invalid Coordinate Event",
        "description": "Testing coordinate boundary enforcement.",
        "country": "Nowhere",
        "region": "Nowhere",
        "latitude": 95.0,  # Invalid: > 90
        "longitude": 10.0,
        "severity": "elevated",
        "confidence": 0.85,
    }
    is_valid, errors = EventValidator.validate_raw_dict(raw)
    assert is_valid is False
    assert any("latitude" in e.lower() for e in errors)

    with pytest.raises(ValidationError):
        EventIngestionService.ingest(raw)


def test_event_validation_out_of_bounds_confidence():
    raw = {
        "title": "Invalid Confidence Event",
        "description": "Testing confidence range check.",
        "country": "Country",
        "region": "Region",
        "latitude": 20.0,
        "longitude": 40.0,
        "severity": "elevated",
        "confidence": 1.5,  # Invalid: > 1.0
    }
    with pytest.raises((ValidationError, Exception)):
        EventIngestionService.ingest(raw)


# ── 2. NORMALIZATION TESTS ───────────────────────────────────────────────────

def test_event_normalization():
    evt = Event(
        event_id="",  # empty id should be autogenerated
        title="  Strait of Hormuz Electronic Jamming Incident  ",
        country="  Iran  ",
        region="  Persian Gulf  ",
        latitude=26.5667123,  # should round to 4 decimals
        longitude=56.2500987,
        severity="critical",
        confidence=0.92,
        affected_assets=["spx ", " vix", "brent "],
        affected_commodities=["brent_crude", " ttf_gas "],
        affected_routes=["  Strait of Hormuz Corridor  "],
    )
    norm = EventNormalizer.normalize_event(evt)
    assert norm.event_id.startswith("evt-")
    assert norm.latitude == 26.5667
    assert norm.longitude == 56.2501
    assert norm.title == "Strait of Hormuz Electronic Jamming Incident"
    assert norm.country == "Iran"
    assert norm.region == "Persian Gulf"
    assert norm.affected_assets == ["SPX", "VIX", "BRENT"]
    assert norm.affected_commodities == ["BRENT_CRUDE", "TTF_GAS"]
    assert norm.affected_routes == ["Strait of Hormuz Corridor"]


# ── 3. EXPLICIT FACTOR FEATURE CALCULATION ───────────────────────────────────

def test_explicit_factors_stored_separately():
    evt = Event(
        event_id="evt-fact-01",
        title="Bab el-Mandeb Anti-Ship Ballistic Attack",
        description="Missile strike targeted commercial container vessel.",
        country="Yemen",
        region="Middle East",
        latitude=12.6,
        longitude=43.3,
        severity="critical",
        confidence=0.95,
        affected_assets=["SPX", "VIX", "BRENT"],
        affected_commodities=["BRENT_CRUDE", "TTF_GAS", "CONTAINER_SCFI"],
        affected_routes=["Bab el-Mandeb"],
    )

    components: RiskSignalComponent = FeatureCalculator.calculate_components(evt, current_regime="ELEVATED")

    # Verify each of the 8 explicit factors exists independently
    assert isinstance(components.event_intensity, float)
    assert 0.0 <= components.event_intensity <= 100.0

    assert isinstance(components.country_exposure, float)
    assert 0.0 <= components.country_exposure <= 100.0

    assert isinstance(components.commodity_exposure, float)
    assert 0.0 <= components.commodity_exposure <= 100.0

    assert isinstance(components.asset_exposure, float)
    assert 0.0 <= components.asset_exposure <= 100.0

    assert isinstance(components.route_exposure, float)
    assert 0.0 <= components.route_exposure <= 100.0

    assert isinstance(components.historical_response, float)
    assert 0.0 <= components.historical_response <= 100.0

    assert isinstance(components.regime_multiplier, float)
    assert components.regime_multiplier == 1.20

    assert isinstance(components.confidence, float)
    assert components.confidence == 0.95

    # Confirm backward-compatible alias sync
    assert components.market_sensitivity == components.asset_exposure


# ── 4. EXPLAINABLE RISK SCORING (NO BLACK BOX) ──────────────────────────────

def test_explainable_risk_scoring_deterministic():
    comp = RiskSignalComponent(
        event_intensity=92.0,
        country_exposure=88.0,
        commodity_exposure=85.0,
        asset_exposure=75.0,
        route_exposure=90.0,
        historical_response=80.0,
        regime_multiplier=1.20,
        confidence=0.95,
    )

    score_1, level_1, drivers_1 = ExplainableRiskScorer.compute_score(comp)
    score_2, level_2, drivers_2 = ExplainableRiskScorer.compute_score(comp)

    # Deterministic reproducibility check (zero randomness)
    assert score_1 == score_2
    assert level_1 == level_2 == "critical"
    assert drivers_1 == drivers_2
    assert len(drivers_1) >= 3

    # Check that score falls within [0, 100]
    assert 0.0 <= score_1 <= 100.0


# ── 5. TRANSMISSION-PATH GENERATION ──────────────────────────────────────────

def test_transmission_path_generation():
    evt = Event(
        event_id="evt-trans-01",
        title="Suez Canal Grounding Anomaly",
        description="Container ship blocking southern channel.",
        country="Egypt",
        region="North Africa",
        latitude=31.2,
        longitude=32.3,
        severity="elevated",
        confidence=0.90,
        affected_assets=["SPX", "VIX"],
        affected_commodities=["BRENT_CRUDE"],
        affected_routes=["Suez Canal"],
        transmission_channels=[
            "Vessel Grounding Incident",
            "Suez Northbound Convoy Suspension",
            "European Bunker Surcharge Repricing",
            "Equity Volatility Spillover",
        ],
    )

    path = TransmissionGenerator.generate_path(evt)
    assert len(path) == 3
    assert path[0].from_node == "Vessel Grounding Incident"
    assert path[0].to_node == "Suez Northbound Convoy Suspension"
    assert path[0].link_type == "geopolitical_shock"
    assert path[1].link_type == "supply_disruption"
    assert path[2].link_type == "price_transmission"
    for link in path:
        assert link.explanation and len(link.explanation) > 10


# ── 6. FULL MANUAL WORKFLOW END-TO-END ───────────────────────────────────────

def test_manual_workflow_end_to_end():
    raw_payload = {
        "title": "Strait of Malacca Convoy Electronic Anomaly",
        "description": "Electronic warfare jamming impacting transshipment traffic.",
        "country": "Singapore",
        "region": "Southeast Asia",
        "latitude": 1.35,
        "longitude": 103.82,
        "severity": "high",
        "confidence": 0.91,
        "affected_assets": ["BRENT", "SPX"],
        "affected_commodities": ["BRENT_CRUDE", "CONTAINER_SCFI"],
        "affected_routes": ["Strait of Malacca"],
    }

    result = EventWorkflow.execute_manual_workflow(raw_payload)

    # Verify structured output matches Phase 2 spec:
    assert "risk_score" in result
    assert "risk_level" in result
    assert "confidence" in result
    assert "drivers" in result
    assert "affected_assets" in result
    assert "affected_commodities" in result
    assert "transmission_path" in result

    assert isinstance(result["risk_score"], float)
    assert result["risk_level"] in ["critical", "high", "elevated", "moderate", "low", "info"]
    assert result["confidence"] == 0.91
    assert len(result["drivers"]) > 0
    assert len(result["affected_assets"]) == 2
    assert len(result["affected_commodities"]) == 2
    assert len(result["transmission_path"]) >= 1

    # Verify persistence into intel store
    persisted_event = intel_store.get_event(result["event"].event_id)
    assert persisted_event is not None
    assert persisted_event.title == "Strait of Malacca Convoy Electronic Anomaly"

    persisted_signal = intel_store.get_signal(result["signal"].signal_id)
    assert persisted_signal is not None
    assert persisted_signal.risk_score == result["risk_score"]


# ── 7. FASTAPI API INTEGRATION TESTS ─────────────────────────────────────────

def test_api_post_manual_event():
    payload = {
        "title": "Red Sea Drone Patrol Probes",
        "description": "Tactical maritime drones shadowed commercial tankers near Hodeidah.",
        "country": "Yemen",
        "region": "Middle East",
        "latitude": 14.8,
        "longitude": 42.9,
        "severity": "critical",
        "confidence": 0.96,
        "affected_assets": ["BRENT", "VIX"],
        "affected_commodities": ["BRENT_CRUDE"],
        "affected_routes": ["Southern Red Sea Route"],
    }

    res = client.post("/api/events", json=payload)
    assert res.status_code == 201
    data = res.json()
    assert "event_id" in data
    assert data["title"] == "Red Sea Drone Patrol Probes"

    # Query the intelligence endpoint
    intel_res = client.get(f"/api/events/{data['event_id']}/intelligence")
    assert intel_res.status_code == 200
    intel_data = intel_res.json()
    assert intel_data["risk_score"] > 0
    assert intel_data["risk_level"] == "critical"
    assert intel_data["confidence"] == 0.96
    assert len(intel_data["drivers"]) > 0
    assert len(intel_data["transmission_path"]) > 0


def test_api_get_signal_by_map_node_id():
    """Validates that clicking ANY signal node on the map retrieves the real backend object."""
    nodes = ["taiwan-strait", "red-sea-mandeb", "strait-hormuz", "panama-canal"]
    for node_id in nodes:
        res = client.get(f"/api/signals/{node_id}")
        assert res.status_code == 200
        sig = res.json()
        assert sig["signal_id"] is not None
        assert sig["risk_score"] > 0
        assert "components" in sig
        assert "transmission_path" in sig

        # Explicit factor verification
        comp = sig["components"]
        assert "event_intensity" in comp
        assert "country_exposure" in comp
        assert "commodity_exposure" in comp
        assert "asset_exposure" in comp
        assert "route_exposure" in comp
        assert "historical_response" in comp
        assert "regime_multiplier" in comp
        assert "confidence" in comp
